// <auto-generated />
namespace Meninx.BookInventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddGetBooksStoredProcedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGetBooksStoredProcedure));
        
        string IMigrationMetadata.Id
        {
            get { return "202308281313325_AddGetBooksStoredProcedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
